/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package visao;

//import controle.Handler;
import java.awt.Color;
import java.awt.Font;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
//import modelo.JogoVelha;

/**
 *
 * @author guilh
 */
public class Janela extends javax.swing.JFrame implements Observer{

    public static final String JOGADOR1 = "o";
    public static final String JOGADOR2 = "x";
    private JButton[][] tabuleiro;
    private JogoVelha jogo;
    private Handler handler;
    
    public Janela(JogoVelha jogo, Handler handler) {
        initComponents();
        
        this.jogo = jogo;
        jogo.addObserver(this);
        this.handler = handler;
        
        jLabel1.setFont(new Font("Arial", Font.BOLD, 14));
        jLabel1.setSize(100, 20);
        jLabel1.setText("");
        
        jToggleButton1.setFont(new Font("Arial", Font.BOLD, 48));
        jToggleButton1.setText(JOGADOR1);
        jToggleButton1.setSelected(true);
        jToggleButton1.setActionCommand(JOGADOR1);
        jToggleButton1.setEnabled(false);
        
        jToggleButton2.setFont(new Font("Arial", Font.BOLD, 48));
        jToggleButton2.setText(JOGADOR2);
        jToggleButton2.setActionCommand(JOGADOR2);
        jToggleButton2.setEnabled(false);
        
        tabuleiro = new JButton[3][3];
        tabuleiro[0][0] = jButton1;
        tabuleiro[0][1] = jButton2;
        tabuleiro[0][2] = jButton3;
        tabuleiro[1][0] = jButton4;
        tabuleiro[1][1] = jButton5;
        tabuleiro[1][2] = jButton6;
        tabuleiro[2][0] = jButton7;
        tabuleiro[2][1] = jButton8;
        tabuleiro[2][2] = jButton9;
        
        
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                String name = String.valueOf(i) + String.valueOf(j);
                tabuleiro[i][j].setFont(new Font("Arial", Font.BOLD, 22));
                tabuleiro[i][j].setText("");
                tabuleiro[i][j].setBackground(Color.GRAY);
                tabuleiro[i][j].addActionListener(handler);
                tabuleiro[i][j].setActionCommand(jToggleButton1.getActionCommand());
                tabuleiro[i][j].setName(name);
            }
        }
        
        jButton10.setFont(new Font("Arial", Font.BOLD, 14));
        jButton10.setText("Limpar");
        jButton10.setVisible(false);
        jButton10.addActionListener(handler);
        jButton10.setActionCommand("Limpar");
        
        jButton11.setFont(new Font("Arial", Font.BOLD, 14));
        jButton11.setText("Sair");
        jButton11.addActionListener(handler);
        jButton11.setActionCommand("Sair");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        jButton11.setText("jButton11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButton1, jToggleButton2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jToggleButton1, jToggleButton2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton10, jButton11, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public void update(Observable obs, Object obj){
        jButton10.setVisible(false);
        jLabel1.setText("");
        int cont = 0;
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                tabuleiro[i][j].setText(jogo.getTabuleiro()[i][j]);
                if(!tabuleiro[i][j].getText().equals("")){
                    tabuleiro[i][j].setBackground(Color.red);
                    tabuleiro[i][j].setEnabled(false);
                    cont++;
                }else{
                    tabuleiro[i][j].setBackground(Color.GRAY);
                    tabuleiro[i][j].setEnabled(true);
                }
            }
        }
        if(jToggleButton1.isSelected()){
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(true); 
            for(int i=0;i<3;i++){
                for(int j=0;j<3;j++){
                    tabuleiro[i][j].setActionCommand(jToggleButton2.getActionCommand());
                }
            }
        }else{
            jToggleButton2.setSelected(false);
            jToggleButton1.setSelected(true);
             for(int i=0;i<3;i++){
                for(int j=0;j<3;j++){
                    tabuleiro[i][j].setActionCommand(jToggleButton1.getActionCommand());
                }
            }
        }
            
        if((cont == 9) || (jogo.verificaFimDeJogo().equals(JOGADOR1)) || (jogo.verificaFimDeJogo().equals(JOGADOR2))){
            for(int i=0;i<3;i++){
                for(int j=0;j<3;j++){
                    tabuleiro[i][j].setEnabled(false);
                }
            }
            jButton10.setVisible(true);
            switch(jogo.verificaFimDeJogo()){
                case "o" : jLabel1.setText("JOGADOR1 Venceu!");
                            break;
                case "x" : jLabel1.setText("JOGADOR2 Venceu!");
                            break;
                case "empate" : jLabel1.setText("Empate!");
            }
        }
    }
    
}
